[tool.poetry]
name = "lumina"
version = "0.1.0"
description = ""
authors = ["Will Pimblett <will@wjdp.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.71.0"
mangum = "^0.12.3"
pydantic = {extras = ["email"], version = "^1.9.0"}
pyhumps = "^3.5.0"
PyJWT = "^2.3.0"
cryptography = "^36.0.1"
requests = "^2.27.1"
boto3 = {extras = ["ssm"], version = "^1.20.32"}
moto = {extras = ["ssm"], version = "^2.3.1"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
uvicorn = "^0.16.0"
mypy = "^0.931"
freezegun = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.9"
files = "src"
pretty = true
ignore_missing_imports = true
