AWSTemplateFormatVersion: "2010-09-09"
Description: lumina

Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        STAGE_NAME: !Ref Environment
        VCS_REV: !Ref VcsRev

# Here we specify the different environment that we have
Parameters:
  Environment:
    Type: String
  VcsRev:
    Type: String

Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Join ["", ["lumina-endpoint-", !Ref Environment]]
      StageName: !Ref Environment

  PythonDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Join ["", ["lumina-dependencies-", !Ref Environment]]
      Description: Dependencies for Lumina
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9

  LuminaMember:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Join ["", ["LuminaMember-", !Ref Environment]]
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: target_type
          AttributeType: S
        - AttributeName: target_id
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: gsi_sk
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: gsi_submission_target
          KeySchema:
            - AttributeName: target_type
              KeyType: HASH
            - AttributeName: target_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  LuminaService:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["", ["lumina-", !Ref Environment]]
      CodeUri: src/
      Handler: handler.handler
      Runtime: python3.9
      Layers:
        - !Ref PythonDependencyLayer
      Policies:
        - KMSDecryptPolicy:
            KeyId: f45fa5dd-e730-4e79-93f0-e24d2079e4c6
        - SSMParameterReadPolicy:
            ParameterName: "lumina/*"
        - SESCrudPolicy:
            IdentityName: nthp@wjdp.uk
        - DynamoDBCrudPolicy:
            TableName: !Ref LuminaMember
      Events:
        LuminaEndpointGet:
          Type: Api
          Properties:
            Path: /{path+}
            Method: get
            RestApiId: !Ref BasicAWSApiGateway
        LuminaEndpointPut:
          Type: Api
          Properties:
            Path: /{path+}
            Method: put
            RestApiId: !Ref BasicAWSApiGateway
        LuminaEndpointPatch:
          Type: Api
          Properties:
            Path: /{path+}
            Method: patch
            RestApiId: !Ref BasicAWSApiGateway
        LuminaEndpointPost:
          Type: Api
          Properties:
            Path: /{path+}
            Method: post
            RestApiId: !Ref BasicAWSApiGateway
        LuminaEndpointDelete:
          Type: Api
          Properties:
            Path: /{path+}
            Method: delete
            RestApiId: !Ref BasicAWSApiGateway
        LuminaEndpointOptions:
          Type: Api
          Properties:
            Path: /{path+}
            Method: options
            RestApiId: !Ref BasicAWSApiGateway

Transform:
  - AWS::Serverless-2016-10-31
